ProjectFlavio/ProjectFlavio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view),
    path('tarefas/', include("tarefas.urls")),

]

ProjectFlavio/tarefas/urls.py
from django.urls import path
from . import views

app_name = "tarefas"
urlpatterns = [
    path("", views.tarefas_home, name='home'),
    path("adicionar/", views.tarefas_adicionar, name="adicionar"),
    path('remover/<int:id>',views.tarefas_remover, name='remover'),
    path("editar/<int:id>", views.tarefas_editar, name="editar"),
]

ProjectFlavio/tarefas/models.py
from django.db import models

# Create your models here.
class TarefaModel(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    completo = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

ProjectFlavio/tarefas/forms.py
from django import forms
from .models import TarefaModel

class TarefaForm(forms.ModelForm):
    class Meta:
        model = TarefaModel
        fields = ['nome', 'descricao', 'completo']

ProjectFlavio/ProjectFlavio/views.py
from django.http import HttpResponse

def index_view(request):
    return HttpResponse("<h1> Bem Vindo!</h1>")

ProjectFlavio/tarefas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TarefaForm
from .models import TarefaModel
from django.http import HttpRequest
# Create your views here.

def tarefas_home(request):
    contexto = {
        'nome': 'Flávio',
        'tarefas': TarefaModel.objects.all()
    }
    return render(request,'tarefas/home.html', contexto)

def tarefas_adicionar(request:HttpRequest):

    if request.method == 'POST':
        formulario = TarefaForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('tarefas:home')

    contexto = {
        "form": TarefaForm
    }
    return render(request, 'tarefas/adicionar.html', contexto)

def tarefas_remover(request:HttpRequest, id):
    tarefa = get_object_or_404(TarefaModel, id=id)
    tarefa.delete()
    return redirect('tarefas:home')

def tarefas_editar(request:HttpRequest, id):
    tarefa = get_object_or_404((TarefaModel), id=id)
    if request.method == 'POST':
        formulario = TarefaForm(request.POST, instance=tarefa)
        if formulario.is_valid():
            formulario.save()
            return redirect('tarefas:home')

    formulario = TarefaForm(instance=tarefa)
    context = {
        "form": formulario,
    }
    return render(request, 'tarefas/editar.html', context)

ProjectFlavio/templates/tarefas/adicionar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
</head>
<body>
    <h1>Adicione suas tarefas aqui!</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

ProjectFlavio/templates/tarefas/editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
</head>
<body>
    <h1>Editar Tarefa</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

ProjectFlavio/templates/tarefas/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Titulo</title>
</head>
<body>
    <h1>Bem vindo {{nome}}, a sua Lista de Tarefas!</h1>
    <h2>Lista de Tarefas</h2>
    <a href="{% url 'tarefas:adicionar' %}">Adicionar Tarefa</a>
    <table border="1">
        <thead>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Data de Criação</th>
            <th>Situação de Conclusão</th>
        </thead>
        <tbody>
            {% for tarefa in tarefas %}
                <tr>
                    <td>{{ tarefa.nome }}</td>
                    <td>{{ tarefa.descricao }}</td>
                    <td>{{ tarefa.data_criacao }}</td>
                    <td>{{ tarefa.completo|yesno:"Concluída,Não Concluída" }}</td>
                    <td><a href="{% url 'tarefas:editar' tarefa.id %}">Editar</a></td>
                    <td><a href="{% url 'tarefas:remover' tarefa.id %}">Remover</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
</body>
</html>